// <auto-generated />
using System;
using ApiAlumnos2026.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiAlumnos2026.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425193503_FechaAlumno")]
    partial class FechaAlumno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiAlumnos2026.Models.Alumno", b =>
                {
                    b.Property<int>("AlumnoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumnoID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.HasKey("AlumnoID");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("ApiAlumnos2026.Models.Asignatura", b =>
                {
                    b.Property<int>("AsignaturaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsignaturaID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.HasKey("AsignaturaID");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("ApiAlumnos2026.Models.Docente", b =>
                {
                    b.Property<int>("DocenteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocenteID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.HasKey("DocenteID");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("ApiAlumnos2026.Models.NotaAlumno", b =>
                {
                    b.Property<int>("NotaAlumnoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotaAlumnoID"));

                    b.Property<int>("AlumnoID")
                        .HasColumnType("int");

                    b.Property<int>("AsignaturaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Nota")
                        .HasColumnType("float");

                    b.HasKey("NotaAlumnoID");

                    b.HasIndex("AlumnoID");

                    b.HasIndex("AsignaturaID");

                    b.ToTable("NotasAlumnos");
                });

            modelBuilder.Entity("ApiAlumnos2026.Models.NotaAlumno", b =>
                {
                    b.HasOne("ApiAlumnos2026.Models.Alumno", "Alumno")
                        .WithMany("NotasAlumnos")
                        .HasForeignKey("AlumnoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiAlumnos2026.Models.Asignatura", "Asignatura")
                        .WithMany("NotasAlumnos")
                        .HasForeignKey("AsignaturaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("ApiAlumnos2026.Models.Alumno", b =>
                {
                    b.Navigation("NotasAlumnos");
                });

            modelBuilder.Entity("ApiAlumnos2026.Models.Asignatura", b =>
                {
                    b.Navigation("NotasAlumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
